export {RecommendedFoods} from "./Recommended-Foods"
export {RoomOccupancy} from "./Room-Occupancy"
export {Scanners} from "./Scanners"
export {QrCodeScanner} from "./Scanners/QrCodeScanner"
export {FaceAttd} from "./Face-Recog"